name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install sphinx sphinx_rtd_theme sphinx-autodoc-typehints

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html

      - name: Upload pages content as an artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
